package com.app.datadistribution.enums;

public enum PermissionType {
    AUTH_READ,
    AUTH_CREATE,
    AUTH_UPDATE,
    AUTH_DELETE,
    
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_ASSIGN_PERMISSION,
    
    PERMISSION_READ,
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,
    
    LEAD_READ,
    LEAD_CREATE,
    LEAD_UPDATE,
    LEAD_DELETE,
    LEAD_ASSIGN,
    LEAD_STATUS_CHANGE,
    LEAD_FEEDBACK_CREATE,
    LEAD_FOLLOWUP_CREATE,
    LEAD_HISTORY_READ,
    
    LEADSOURCE_READ,
    LEADSOURCE_CREATE,
    LEADSOURCE_UPDATE,
    LEADSOURCE_DELETE,
    
    USER_ROLE_ASSIGN,

    COURSE_VIEW,
    COURSE_CREATE,
    COURSE_UPDATE,
    COURSE_DELETE,

    COURSE_TYPE_VIEW,
    COURSE_TYPE_CREATE,
    COURSE_TYPE_UPDATE,
    COURSE_TYPE_DELETE,

    FOLLOWUP_VIEW,
    FOLLOWUP_CREATE,
    FOLLOWUP_UPDATE,
    FOLLOWUP_DELETE,

    FEEDBACK_VIEW,
    FEEDBACK_CREATE,
    FEEDBACK_UPDATE,
    FEEDBACK_DELETE
}

