package com.app.datadistribution.enums;

public enum PermissionType {
    AUTH_READ,
    AUTH_CREATE,
    AUTH_UPDATE,
    AUTH_DELETE,
    
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_ASSIGN_PERMISSION,
    
    PERMISSION_READ,
    PERMISSION_CREATE,
    PERMISSION_UPDATE,
    PERMISSION_DELETE,
    
    LEAD_READ,
    LEAD_CREATE,
    LEAD_UPDATE,
    LEAD_DELETE,
    LEAD_ASSIGN,
    LEAD_STATUS_CHANGE,
    LEAD_FEEDBACK_CREATE,
    LEAD_FOLLOWUP_CREATE,
    LEAD_HISTORY_READ,

    LEAD_STATUS_VIEW,
    LEAD_STATUS_CREATE,
    LEAD_STATUS_UPDATE,
    LEAD_STATUS_DELETE,
    LEAD_STATUS_HISTORY_VIEW,
    
    LEADSOURCE_READ,
    LEADSOURCE_CREATE,
    LEADSOURCE_UPDATE,
    LEADSOURCE_DELETE,
    
    USER_ROLE_ASSIGN,

    COURSE_VIEW,
    COURSE_CREATE,
    COURSE_UPDATE,
    COURSE_DELETE,

    COURSE_TYPE_VIEW,
    COURSE_TYPE_CREATE,
    COURSE_TYPE_UPDATE,
    COURSE_TYPE_DELETE,

    FOLLOWUP_VIEW,
    FOLLOWUP_CREATE,
    FOLLOWUP_UPDATE,
    FOLLOWUP_DELETE,

    FEEDBACK_VIEW,
    FEEDBACK_CREATE,
    FEEDBACK_UPDATE,
    FEEDBACK_DELETE,

    BOARD_VIEW,
    BOARD_CREATE,
    BOARD_UPDATE,
    BOARD_DELETE,

    GRADE_VIEW,
    GRADE_CREATE,
    GRADE_UPDATE,
    GRADE_DELETE,

    DASHBOARD_VIEW,
    DASHBOARD_VIEW_ALL,
    DASHBOARD_VIEW_DEPARTMENT,
    DASHBOARD_COURSE_TYPE_VIEW,
    DASHBOARD_CARD_VIEW,
    DASHBOARD_CARD_PREFERENCE_UPDATE,
    DASHBOARD_CARD_ORDER_UPDATE,
    DASHBOARD_USER_PREFERENCE_MANAGE,

    LEAD_INTERESTED_COURSE_UPDATE,
    LEAD_REGISTERED_COURSE_UPDATE,

    COURSE_TEMPLATE_VIEW,
    COURSE_TEMPLATE_CREATE,
    COURSE_TEMPLATE_UPDATE,
    COURSE_TEMPLATE_DELETE,
    COURSE_TEMPLATE_SEND,

    COURSE_IMAGE_VIEW,
    COURSE_IMAGE_UPLOAD,
    COURSE_IMAGE_UPDATE,
    COURSE_IMAGE_DELETE,
    COURSE_TEMPLATE_IMAGE_SELECT,

    COURSE_USP_VIEW,
    COURSE_USP_CREATE,
    COURSE_USP_UPDATE,
    COURSE_USP_DELETE,

    COURSE_TEMPLATE_SEND_EMAIL,
    COURSE_TEMPLATE_SEND_WHATSAPP,

    // Department Management & Data Access Permissions
    DEPARTMENT_VIEW,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,
    DEPARTMENT_USER_VIEW,
    DEPARTMENT_USER_ASSIGN,
    DEPARTMENT_USER_REMOVE,
    DEPARTMENT_HOD_VIEW,
    DEPARTMENT_COUNSELLOR_VIEW,
    DEPARTMENT_DATA_VIEW,
    DEPARTMENT_DATA_CREATE,
    DEPARTMENT_DATA_UPDATE,
    DEPARTMENT_DATA_DELETE
}
