package com.app.datadistribution.enums;

public enum PermissionType {
    AUTH_READ,
    AUTH_CREATE,
    AUTH_UPDATE,
    AUTH_DELETE,
    
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    
    LEAD_READ,
    LEAD_CREATE,
    LEAD_UPDATE,
    LEAD_DELETE,
    LEAD_ASSIGN,
    LEAD_STATUS_CHANGE,
    LEAD_FEEDBACK_CREATE,
    LEAD_FOLLOWUP_CREATE,
    LEAD_HISTORY_READ,
    
    LEAD_SOURCE_READ,
    LEAD_SOURCE_CREATE,
    LEAD_SOURCE_UPDATE,
    LEAD_SOURCE_DELETE,
    LEAD_SOURCE_STATS
}
