# ==============================================
# Application Info
# ==============================================
spring.application.name=DataDistributionSystem

# ==============================================
# Database Configuration (MySQL)
# ==============================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/CMS_PROJECT_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:RcefRoot@2026!}
spring.datasource.password=${DB_PASSWORD:Root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================
# Connection Pooling (HikariCP)
# ==============================================
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:20}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN:5}
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# ==============================================
# Hibernate / JPA
# ==============================================
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================================
# Mail Configuration (Gmail / Google Workspace)
# ==============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:chancelloroffice@renaissance.ac.in}
spring.mail.password=${MAIL_PASSWORD:nixjsjxyddpvwvpe}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==============================================
# JWT Configuration
# ==============================================
jwt.secret=${JWT_SECRET:2x9zV7kQyt8qEktJBSzGeJKaVzMeEVFkh0FcogLPBQzX8p2mW3nY5tR7uC9vA1bD4eF6gH8iJ0kL2mN4oP6qR8sT0uV2wX4yZ6aB8cD0eF2gH4iJ6k}
jwt.refresh.expiration=604800000

# ==============================================
# Logging
# ==============================================
logging.level.org.springframework=${LOG_LEVEL_SPRING:INFO}
logging.level.org.hibernate.SQL=${LOG_LEVEL_SQL:INFO}
logging.level.org.hibernate.orm.jdbc.bind=${LOG_LEVEL_BIND:INFO}

# ==============================================
# Server Config
# ==============================================
server.port=${SERVER_PORT:8082}
server.address=0.0.0.0
